### PR TITLE
Fix E2E tests (WP - v5.9.3 & GF v 2.6)

### LINKED ISSUE #1312: Fix E2E Tests for WP5.9 and GF2.6-beta1
**Description**
There's still a number of E2E tests that are failing https://github.com/GravityPDF/gravity-pdf/runs/5001371189?check_suite_focus=true after the update to WP5.9 and GF2.6 in our automated testing suite.

I fixed a few in https://github.com/GravityPDF/gravity-pdf/pull/1311 but ran into a problem [where the Selector being used](https://github.com/GravityPDF/gravity-pdf/blob/development/tests/e2e/advanced-checks/confirmation-shortcode.test.js#L56) was no longer working, but the element trying to be matched did in fact appear on the page with what appeared to be the correct markup.

@debbieellis7 as you've significantly more experience with the E2E tests and testcafe then me, could you take a look at where the problem lies?

### PR DESCRIPTION
**Pull request by debbieellis7**
## Description
Resolves: #1312 (Fix E2E Tests for WP5.9 and GF2.6)

## Testing instructions
Run: **yarn test:e2e**
Run: **yarn test:e2e:headless**

## Checklist:
- [x] I've tested the code.
- [ ] My code is easy to read, follow, and understand
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation / docblocks.

### CODE REVIEW

**Comment by debbieellis7** [comment]
Node v16 (Latest recommended version) dropped the support for 'fiber' https://github.com/GravityPDF/gravity-pdf/blob/e418d25634492328b2f5fe74246de4b839e2cde3/webpack.config.js#L43 which will prompt an error when rebuilding JS.

I temporarily remove 'fiber' from our Webpack setup which will cause a slower bundling speed.

@jakejackson1 @jestonihpi

**Comment by debbieellis7** [comment]
WIP

**Comment by jakejackson1** [comment]
> Node v16 (Latest recommended version) dropped the support for 'fiber'
> 
> https://github.com/GravityPDF/gravity-pdf/blob/e418d25634492328b2f5fe74246de4b839e2cde3/webpack.config.js#L43
> 
> which will prompt an error when rebuilding JS.
> I temporarily remove 'fiber' from our Webpack setup which will cause a slower bundling speed.
> 
> @jakejackson1 @jestonihpi

The Gravity PDF node environment is currently meant to be run with Node 12 and our tooling hasn't been updated to run a more modern version yes.

**Comment by jakejackson1** [comment]
@debbieellis7 I've pushed a change that will help people identify that Node 12 is required https://github.com/GravityPDF/gravity-pdf/pull/1334

**Pull request merged**
