### PR TITLE
Add Payment Status and Payment Amount Conditional Logic options

### LINKED ISSUE #1404: Add Entry Meta as PDF Conditional Logic Options
**Description**
There are a number of missing conditional options missing from Gravity PDF's Conditional Logic feature that can be found on the Entry List search list. For example, we are unable to disable PDFs if the Payment Status isn't set to "Paid".

**Expected behavior**
To be able to add conditional logic on this meta data.

**Screenshots**
Screen Shot 2022-08-19 at 4 13 38 pm

### PR DESCRIPTION
**Pull request by jakejackson1**
## Description

This PR registers two new choices in the conditional logic selector:

1. Payment Status
2. Payment Amount

I've opted not to include additional entry meta like Entry ID, or Entry Date, at this stage as it requires additional work to support. This PR just focuses on the most important meta data.

TODO:

- [ ] Check if conditional logic will pass as is, or if we need to hook into Gravity Forms and make some tweaks when the logic is being parsed
- [ ] Write E2E test

Partially resolves #1404 

## Checklist:
- [ ] I've tested the code.
- [ ] My code is easy to read, follow, and understand
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation / docblocks.

### CODE REVIEW

**Comment by jakejackson1** [comment]
@jestonihpi looks like Gravity Wiz strikes again! They have done something similar with their snippets: https://github.com/gravitywiz/snippet-library/blob/master/gravity-forms/gw-conditional-logic-entry-meta.php#L165-L179. Note: there's currently no license included with this snippet, so use it as a reference for how you hook into Gravity Forms to add custom conditional logic.

**Comment by jestonihpi** [comment]
@jakejackson1 . Woot! noted.

**Comment by jakejackson1** [comment]
@jestonisumande pair your work down to just Payment Status and Payment Amount for now.

**Comment by jestonihpi** [comment]
Copy @jakejackson1 .

**Pull request closed without merging**
